### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by patrickschur** [mamamia5x/Old-HTML5-Compiler#1]
When I open and execute your project I get the following message inside of your editor:

```
<br />
<b>Warning</b>:  file_get_contents(file.html
): failed to open stream: No such file or directory in <b>/var/www/html/phpdesktop-linux-72.1/www/index.php</b> on line <b>39</b><br />
```

These are the two lines where the error occurs.

```php
$current = file_get_contents('leaveAloneCompiler/filename.txt');
echo file_get_contents($current);
```

The `$current` variable contains not only the filename but also a newline at the end.

###  How to fix this issue?

Remove the newline at the end of the `filename.txt` file or use the `trim` function to remove unnecessary whitespaces.

For example:

```php
echo file_get_contents(trim($current));
```

**Comment by mamamia5x** [comment]
This is due to the actual PHP thing I use. If you do it online, this doesn't show.

**Comment by mamamia5x** [comment]
It creates the file by itself, so if you press save, it'll create the file.
