### ISSUE TITLE
Warnings during update process

### ISSUE THREAD

**Issue by patrickschur** [mamamia5x/Old-HTML5-Compiler#2]
When I press the `Update` button I get the following warnings:

![image](https://user-images.githubusercontent.com/18181635/73077485-8be67280-3ec0-11ea-877d-9afda34aeb1e.png)

I'm not exactly sure why this happens but I think that has something to do with a missing openssl extension in `phpdesktop`. I tried to get it running with executing the `php-cgi-with-ext` binary but this does nothing at all.

It would be great if you could add an installation guide for people using Linux. By the way I'm using Ubuntu 18.04.3 LTS and PHP 7.2.24.

**Comment by mamamia5x** [comment]
Yeah, I don't use linux. I gotta check it up. I'll try to fix it.

**Comment by mamamia5x** [comment]
It sometimes does that if I don't run it inside the WWW folder. I'll try to make a fix, I might start using a different PHP runner.

**Comment by patrickschur** [comment]
By the way why do you use phpdesktop and not a normal webserver like apache oder nginx?
