### ISSUE TITLE
Remove render-blocking JavaScript

### ISSUE THREAD

**Issue by patrickschur** [mamamia5x/Old-HTML5-Compiler#3]
Before the browser renders a page it has to build the DOM tree by parsing the HTML. Whenever a script occurs the browser has to stop and execute this script before it can continue parsing the HTML.
I would recommend you to put the all your scripts at the bottom of your `body` or use the `async` and `defer` attributes.

Using the HTML `async` attribute will prevent JavaScript from blocking the parser.

```html
<script async src="example.js"></script>
```

or you can use the HTML `defer` attribute to execute your JavaScript after the page finished loading.

```html
<script defer src="example.js"></script>
```

**Comment by mamamia5x** [comment]
All scripts have async now.

**Comment by patrickschur** [comment]
Great! But you must be careful with using `async`. Because it's async it also means that your scripts can be loaded in different order. Just a notice. :)
