### ISSUE TITLE
Style and layout changes

### ISSUE THREAD

**Issue by patrickschur** [mamamia5x/Old-HTML5-Compiler#5]
When releasing a project like this you should keep an eye on the UI and UX. Here are some tips:

- Don't use red text on blue background because it's hard to read.
- Use another color for the input placeholder. It's even harder to read.
- Input fields should have the same size than your buttons.
- All elements have the same margin except of the first input field.
- The editor and the white box should be on the same level.

![image](https://user-images.githubusercontent.com/18181635/73083626-d02b4000-3ecb-11ea-94ab-179f15b33c07.png)

Here is something I came up with using DevTools when following the tips.

![image](https://user-images.githubusercontent.com/18181635/73088001-b261d900-3ed3-11ea-9e75-d170d1ca1b43.png)

**Comment by mamamia5x** [comment]
I'll fix styling soon.
